### ISSUE TITLE
Usage permission

### ISSUE THREAD

**Issue by JanionNevill** [RinteRface/shinyLocalStorage#2]
Hi,

I found your local storage example to be really helpful, but it currently specifies no license. Would you be happy to add a licence for the code, or give express permission for this to be used please? I want to make use of it for our medical research tools found on the [CRSU GitHub account](https://github.com/CRSU-Apps).

Thanks
Janion

**Comment by DivadNojnarg** [comment]
Thanks for checking. I updated the repo: https://github.com/RinteRface/shinyLocalStorage?tab=MIT-1-ov-file#readme.

**Comment by JanionNevill** [comment]
Thanks so much for getting back so quickly!
